#!/bin/bash
# Script para rodar o auto-test agent localmente e criar PR

set -e

echo "🤖 Auto-Test Agent - Local Execution"
echo "===================================="
echo ""

# 1. Generate coverage
echo "📊 Step 1: Generating coverage data..."
pytest --cov=. --cov-report=json --quiet || true
echo "✅ Coverage generated"
echo ""

# 2. Generate tests
echo "🧠 Step 2: Generating intelligent tests..."
python3 .github/scripts/auto_generate_tests.py
echo ""

# 3. Check if tests were generated
if [ ! -d "tests/unit" ] || [ -z "$(ls -A tests/unit/test_*_auto.py 2>/dev/null)" ]; then
    echo "❌ No tests were generated"
    exit 1
fi

echo "✅ Tests generated successfully!"
echo ""

# 4. Run new tests
echo "🧪 Step 3: Running generated tests..."
pytest tests/unit/test_*_auto.py -v --tb=short || true
echo ""

# 5. Check new coverage
echo "📈 Step 4: Checking new coverage..."
pytest --cov=. --cov-report=term-missing --quiet || true
echo ""

# 6. Create branch and commit
BRANCH_NAME="auto-tests-$(date +%Y%m%d-%H%M%S)"
echo "🔀 Step 5: Creating branch: $BRANCH_NAME"

git checkout -b "$BRANCH_NAME"
git add tests/unit/test_*_auto.py test_generation_summary.md

git commit -m "test: auto-generate tests to improve coverage

Generated by local auto-test agent execution.
Target: Increase coverage to 80%

Tests generated:
- Unit tests for high-priority functions
- Proper mocks and AAA pattern
- Edge cases and error handling

Issue: #1

Generated with: ./run_auto_test_agent.sh"

echo "✅ Changes committed to branch: $BRANCH_NAME"
echo ""

# 7. Push branch
echo "📤 Step 6: Pushing branch to remote..."
git push origin "$BRANCH_NAME"
echo "✅ Branch pushed!"
echo ""

# 8. Show next steps
echo "=========================================="
echo "🎉 Success! Next steps:"
echo ""
echo "Option 1: Create PR via GitHub UI"
echo "  → https://github.com/magacho/mcp-git-server/compare/$BRANCH_NAME"
echo ""
echo "Option 2: Create PR via CLI"
echo "  → gh pr create --base main --head $BRANCH_NAME \\"
echo "       --title '🤖 Auto-generated tests to improve coverage' \\"
echo "       --body 'Generated tests to address #1'"
echo ""
echo "Option 3: Review locally first"
echo "  → pytest tests/unit/test_*_auto.py -v"
echo "  → pytest --cov=. --cov-report=html"
echo "  → open htmlcov/index.html"
echo ""
echo "=========================================="
