# Nome do seu workflow. Aparecerá na aba "Actions" do GitHub.
name: Publicar Imagem Docker Automaticamente

# Gatilhos: Define QUANDO a automação deve rodar.
on:
  # Roda sempre que houver um push na branch 'main'
  # push:
    # branches:
    #   - main
  # Roda sempre que uma nova tag de versão (ex: v1.0.0) for criada
    tags:
      - 'v*.*.*'

jobs:
  # Nome do "trabalho" que será executado
  build-and-push:
    # A automação rodará em uma máquina virtual (runner) com Ubuntu
    runs-on: ubuntu-latest

    steps: # Sequência de passos a serem executados
      # 1. Clona o código do seu repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Faz o login no Docker Hub usando os secrets que você configurou
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Extrai metadados, como tags, para a imagem Docker
      - name: Extrair metadados da imagem
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: flaviomagacho/mcp-git-server

      # 4. Constrói a imagem a partir do seu Dockerfile e publica no Docker Hub
      - name: Construir e publicar a imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: . # Usa o Dockerfile na raiz do projeto
          push: true # Garante que a imagem será publicada (push)
          tags: ${{ steps.meta.outputs.tags }} # Usa as tags geradas no passo anterior (ex: latest, v1.0.1)
          labels: ${{ steps.meta.outputs.labels }}

      # (OPCIONAL, mas recomendado) 5. Atualiza a descrição do repositório no Docker Hub com o seu README.md
      - name: Atualizar descrição no Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: flaviomagacho/mcp-git-server
          readme-filepath: ./README.md